fortigate_instance_ami="auto"
region="cn-hongkong"
activefgtlicense="~/license/FGVMULTM23000023.lic"
passivefgtlicense="~/license/FGVMULTM23000022.lic"
//product="FortiGate.*BYOL.*6.4.12"
product="FortiGate.*BYOL.*7.2.4"
//product="FortiGate.*PAYG.*8.*7.2.4"

key_location="~/.ssh/id_rsa.pub"
custom_rt="1"
num_secondary_instances="1"
eip="1"
mgmt_eip="1"
instance="auto"
